// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReportingService.Data;

#nullable disable

namespace ReportingService.Migrations
{
    [DbContext(typeof(ReportDbContext))]
    [Migration("20230922213219_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ReportingService.Models.Report", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportId"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ReportId");

                    b.ToTable("Reports");

                    b.HasData(
                        new
                        {
                            ReportId = 1,
                            CreatedAt = new DateTime(2023, 9, 22, 23, 32, 19, 276, DateTimeKind.Local).AddTicks(5699),
                            Description = "Sales data for the month",
                            Name = "Monthly Sales",
                            UpdatedAt = new DateTime(2023, 9, 22, 23, 32, 19, 276, DateTimeKind.Local).AddTicks(5746)
                        },
                        new
                        {
                            ReportId = 2,
                            CreatedAt = new DateTime(2023, 9, 22, 23, 32, 19, 276, DateTimeKind.Local).AddTicks(5750),
                            Description = "Revenue data for the quarter",
                            Name = "Quarterly Revenue",
                            UpdatedAt = new DateTime(2023, 9, 22, 23, 32, 19, 276, DateTimeKind.Local).AddTicks(5752)
                        });
                });

            modelBuilder.Entity("ReportingService.Models.ReportDetail", b =>
                {
                    b.Property<int>("ReportDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportDetailId"), 1L, 1);

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReportId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ReportDetailId");

                    b.HasIndex("ReportId");

                    b.ToTable("ReportDetails");

                    b.HasData(
                        new
                        {
                            ReportDetailId = 1,
                            Data = "Some data for Monthly Sales",
                            ReportId = 1,
                            Type = "Table"
                        },
                        new
                        {
                            ReportDetailId = 2,
                            Data = "Some more data for Monthly Sales",
                            ReportId = 1,
                            Type = "Chart"
                        },
                        new
                        {
                            ReportDetailId = 3,
                            Data = "Some data for Quarterly Revenue",
                            ReportId = 2,
                            Type = "Table"
                        });
                });

            modelBuilder.Entity("ReportingService.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "john.doe@example.com",
                            Username = "john_doe"
                        },
                        new
                        {
                            UserId = 2,
                            Email = "jane.doe@example.com",
                            Username = "jane_doe"
                        });
                });

            modelBuilder.Entity("ReportingService.Models.ReportDetail", b =>
                {
                    b.HasOne("ReportingService.Models.Report", "Report")
                        .WithMany("ReportDetails")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("ReportingService.Models.Report", b =>
                {
                    b.Navigation("ReportDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
